setwd('/Users/leichen/Research project/Predictive memory')
compareSimilarity = read_excel('concept similarity matrix.xlsx', sheet='general_similarity_level')
t.test(compareSimilarity$cosine_similarity~compareSimilarity$category)
boxplot(compareSimilarity$cosine_similarity~compareSimilarity$category)
compareSimilarity = read_excel('concept similarity matrix.xlsx', sheet='similarity_level')
t.test(compareSimilarity$tool~compareSimilarity$category)
boxplot(compareSimilarity$tool~compareSimilarity$category)
t.test(compareSimilarity$animal~compareSimilarity$category)
boxplot(compareSimilarity$animal~compareSimilarity$category)
t.test(compareSimilarity$bird~compareSimilarity$category)
boxplot(compareSimilarity$bird~compareSimilarity$category)
t.test(compareSimilarity$kitchen~compareSimilarity$category)
boxplot(compareSimilarity$kitchen~compareSimilarity$category)