trials = [
	{
		list: 1,
		target: 	["Adolescence","Advantage","Ambulance","Arbiter","Assumption","Audit","Basic","Bedroom","Bequest","Broad","Candidate","Chestnut","Christmas","Cigarette","Circumstance","Clean","Cocktail","Commander","Composer","Consequence","Consider","Constant","Context","Cottage","Crush","Deity","Despot","Dirge","Education","Enamel","Essence","Exception","Expanse","Exploration","Factor","Factory","Fashion","Forest","Friction","Gentry","Hostility","Impetus","Institution","Jewel","Keep","Lobster","Merchant","Missile","Money","Mother","Motive","Necklace","Omen","Ordinary","Outcome","Photograph","Plant","Private","Property","Puppy","Refrigerator","Religion","Revolver","River","Rogue","Shrimp","Society","Student","Suffix","Value","Wicket","Winter"],
		synonym: 	["Juvenile","Benefit","Lifeboat","Mediator","Belief","Inspection","Simple","Kitchen","Legacy","Wide","Applicant","Conker","Birthday","Tobacco","Occurrence","Wash","Alcohol","Boss","Musician","Outcome","Think","Regular","Surrounding","Cabin","Squash","Divinity","Tyrant","Lament","Teaching","Coating","Nucleus","Deviation","Vastness","Examination","Part","Workshop","Style","Woods","Drag","Squire","Aggression","Motivation","Establishment","Gem","Save","Crayfish","Dealer","Bomb","Cash","Parent","Incentive","Choker","Portent","Normal","Conclusion","Camera","Tree","Personal","Building","Kitten","Oven","Faith","Pistol","Stream","Scoundrel","Prawn","Public","Pupil","Inflection","Price","Pitch","Summer"],
		foil1: 		["Boss","Condition","Wallet","Undertaking","Irony","Derivation","Recent","Artist","Complication","Fresh","Salvation","Eagle","Kiss","Camera","Incentive","Pass","Orchestra","Crime","Obligation","Diversity","Develop","Essential","Deduction","Holiday","Gasp","Vitriol","Unreality","Emanation","Department","Molasses","Conclusion","Occurrence","Canon","Salvation","Advantage","Meadow","Column","Wine","Dealer","Sedative","Siege","Equity","Happiness","Harp","Become","Bracelet","Engineer","Uncle","Church","Money","Feature","Lemonade","Recess","Previous","Description","Oven","Heart","Strong","Committee","Cider","Birthday","Design","Mist","Doctor","Polka","Nun","Period","Radio","Perpetrator","Purpose","Flora","Clothes"],
		foil2: 		["Reward","Tendency","Ant","Reformation","Introduction","Enigma","Considerable","Grass","Chronology","Evil","Physics","Swamp","Bird","Dentist","Diversity","Send","Peak","Establishment","Stranger","Deviation","Determine","Aware","Outcome","Cop","Blink","Incredulity","Disclosure","Rarity","Front","Labyrinth","Deduction","Preparation","Duel","Civilian","Instance","Bomb","Shelter","Boat","Engineer","Perch","Oath","Misconception","Stranger","Lobster","Put","Helmet","Misery","Mirror","Car","Bed","Preparation","Geese","Benzene","Significant","Discretion","Mirror","Window","Single","Research","Peach","Meadow","Growth","Sunset","Square","Gasket","Pyramid","Air","Summer","Temerity","Effect","Rubble","Sea"],
		frequency: 	["Med","Low","High","Low","Low","Low","Low","High","Low","Med","Med","High","High","High","Low","Med","High","Med","Med","Low","Low","Low","Low","High","Med","Low","Low","Low","Med","Med","Low","Low","Med","Med","Low","High","Med","High","Med","Med","Med","Low","Med","High","Low","High","Med","High","High","High","Low","High","Med","Low","Low","High","High","Med","Med","High","High","Med","High","High","Med","High","Med","High","Low","Low","Med","High"],
		imagability: ["Med","High","Low","Low","Med","Low","High","High","Low","High","Med","Low","Med","Med","Med","High","Med","Med","Med","Med","High","High","Med","Med","Low","Low","Low","Low","High","Low","Med","Med","Low","Med","High","Med","High","High","Med","Low","Low","Low","Med","Low","High","Low","Med","Med","High","High","Med","Low","Low","High","Med","Med","High","High","High","Low","Med","High","Low","High","Low","Low","High","High","Low","High","Low","High"]
	},
	{
		list: 2,
		target: 	["Accordance","Alias","Alternative","Ancient","Aspect","Attribute","Average","Boredom","Butterfly","Cartilage","Cause","Chemistry","Chicken","Child","Citizen","Coffee","Criterion","Definition","Delight","Depression","Distance","Effect","Employment","Emulsion","Engagement","Enthusiasm","Fallacy","Fountain","Freedom","Frog","Function","Gallant","Helmet","Humour","Infidelity","Initiative","Intention","Interim","Kite","Kitten","Landscape","Laughter","Master","Morass","Mountain","Opponent","Pair","Pattern","Policeman","Preliminary","Problem","Proper","Protocol","Quake","Reason","Road","Rock","Satisfaction","Significant","Sister","Strength","Sun","Telephone","Tendency","Tobacco","Tulip","Uncertainty","Valley","Verity","Violin","Window","Zipper"],
		synonym: 	["Harmony","Pseudonym","Substitute","Old","Feature","Trait","Typical","Dullness","Moth","Gristle","Make","Physics","Bird","Kid","Civilian","Tea","Norm","Description","Happiness","Misery","Length","Consequence","Occupation","Paint","Obligation","Passion","Myth","Spray","Independence","Toad","Purpose","Heroic","Headdress","Wit","Adultery","Enterprise","Ambition","Temporary","Toy","Gosling","Scenery","Grin","Professor","Mire","Peak","Foe","Couple","Design","Cop","Introduction","Difficulty","Appropriate","Etiquette","Tremor","Explanation","Street","Stone","Delight","Important","Uncle","Power","Moon","Radio","Trend","Cigar","Daffodil","Ambiguity","Hills","Certainty","Viola","Door","Fastener"],
		foil1: 		["Analogy","Condescension","Discretion","Sweet","Harmony","Preference","Actual","Token","Gym","Madness","Return","Crime","Orange","Road","Passion","Key","Suffix","Enterprise","Reward","Examination","Scene","Difference","Courage","Titbit","Drag","Occupation","Conjugation","Cabin","Month","Jewel","Responsibility","Fertile","Scissors","Carbohydrate","Molecule","Belief","Ambiguity","Reciprocal","Zipper","Sunburn","Orchestra","Palace","Enemy","Substratum","Holiday","Evolution","Master","Conference","Spray","Surrounding","Law","Apparent","Allegory","Buyer","Value","Fire","Bottle","Juvenile","Ordinary","Workshop","Literature","Bridge","Knife","Factor","Scenery","Alligator","Occasion","Baby","Artifice","Shed","Eye","Raspberry"],
		foil2: 		["Substitute","Reprisal","Ambition","Sharp","Occasion","Complication","Latter","Recruit","Volcano","Dowry","Consider","Musician","Cigar","University","Scholar","Neck","Resumption","Tendency","Applicant","Courage","Health","Reason","Delight","Riddle","Distress","Distress","Impropriety","Orange","Aid","Pickle","Extent","Tame","Caterpillar","Whiff","Relic","Analogy","Irony","Indifferent","Squirrel","Ski","Grin","Tobacco","Edge","Gist","Alcohol","Optimism","Childhood","Performance","Dentist","Tendency","Service","Limited","Debacle","Infinity","Influence","Student","Winter","Scholar","Normal","Kiss","Temperature","Horse","Dog","Concept","Palace","Banana","Nucleus","Ship","Mediocrity","Rabbit","Plant","Mosquito"],
		frequency: 	 ["Low","Low","Low","Med","Low","Low","Low","Med","High","Med","Low","Med","High","High","Med","High","Low","Low","Med","Med","Med","Low","Med","Med","Med","Med","Low","High","Med","High","Low","Med","High","Med","Med","Low","Low","Low","High","High","High","High","Med","Low","High","Med","Med","Med","High","Low","Med","Low","Low","Med","Low","High","High","Med","Low","High","Med","High","High","Low","High","High","Low","High","Low","High","High","High"],
		imagability: ["Med","Low","Med","High","Med","Low","High","Low","Low","Low","High","Med","Med","High","Med","High","Low","Med","Med","Med","High","High","Med","Low","Med","Med","Low","Med","High","Low","High","Low","Low","Low","Low","Med","Med","Low","Low","Low","Med","Med","High","Low","Med","Low","High","High","Med","Med","High","High","Low","Low","High","High","High","Med","High","Med","High","High","High","High","Med","Low","Med","High","Low","Low","High","Low"]		
	}
];